# This file declaratively says what performance tests should be run, and where they should be run.
# The tools will work out all permutations of runs from this.
# They will interrogate the database and see what runs already exist.
# Any runs that need running, will be.

servers:
  # This is where the performers should run.  If not "localhost" they will be scp-ed to here, in the form of a tarred Docker image.
  performer: localhost

  driver:
    # Where the driver runs.  Currently only "localhost" is supported.
    hostname: localhost

    # Either the location of a checked-out transactions-fit-performer / perf-sdk project, or "https://github.com/couchbaselabs/transactions-fit-performer"
    # source: https://github.com/couchbaselabs/transactions-fit-performer
#    source: /Users/charliehayes/Documents/GitHub/perf-sdk
    source: /home/couchbase/jenkins/workspace/performance/sdk-performance/perf-sdk


# Generally only CI should be talking to production database.  For local performance testing, spin up a localhost database.
# The password gets replaced by an environment variable when running on CI
database:
  hostname: 54.193.85.254
  port: 5432
  username: postgres
  password: password
  database: perf

environment:
  # Can override any executables here, to workaround environmental/path issues.
  executables:
    getent: /usr/bin/getent
    cbdyncluster: /usr/local/bin/cbdyncluster
#    cbdyncluster: /Users/charliehayes/documents/Test/cbdyncluster-macos
#    docker: /usr/local/bin/docker
    docker: /usr/bin/docker

  # These will be added to environment variables when running executables
  envvar:
#    DOCKER_HOST: cbdyncluster docker-host docker ps

# These settings will not be saved to the database
settings:
  # Outputs what would be performed, without actually performing it.  Config files still get written.
  dryRun: false

  # Whether to ignore whatever runs are already in the database
  force: false

  # If confident that all Docker images are built and up-to-date
  skipDockerBuild: false

matrix:
  clusters:
    - type: cbdyncluster
      version: 7.0-stable
      replicas: 0
      nodes: 1
#    - type: unmanaged
#      hostname: 10.112.212.101

  implementations:
    - language: python
      version: 3.2.4
    # If just port is specified: the performer is expected to be running already at location servers.performer.
    # E.g. this is for localhost testing.
    # Otherwise, specify language and version, and this tool will spinup a performer running at location servers.performer.
#    - port: 8060

  workloads:
    - operations:
      - op: insert
        count: $doc_num
    - operations:
        - op: get
          count: $doc_num
    - operations:
        - op: remove
          count: $doc_num
    - operations:
        - op: replace
          count: $doc_num


variables:
  custom:
    - name: doc_num
      value: 100000
  predefined:
    - name: horizontal_scaling
      value: 1
