# This file declaratively says what performance tests should be run, and where they should be run.
# The tools will work out all permutations of runs from this.
# They will interrogate the database and see what runs already exist.
# Any runs that need running, will be.

servers:
  # This is where the performers should run.  Currently only "localhost" is supported.
  # In future we want to supported scp-ing the performers to a remote host.
  performer: localhost

  driver:
    # Where the driver runs.  Currently only "localhost" is supported.
    hostname: localhost

    # WARNING: files under this location will be modified.  Make sure you have a backup or have committed local changes.
    # Under this location will need these folders:
    #
    # transactions-fit-performer
    #
    # If want to test JVM:
    # couchbase-jvm-clients
    #
    # If want to test .NET:
    # couchbase-net-client
    # WARNING: It will automatically delete and re-checkout the directory 'couchbase-net-client' under here   (if need to run .NET performer)
    #          As the .NET performer requires this directory structure.
    source: /home/ec2-user

# Generally only CI should be talking to production database.  For local performance testing, spin up a localhost database.
# The password gets replaced by an environment variable when running on CI
database:
  # When run by jenkins-sdk, jenkins-sdk will use `hostname`, and the driver will use `hostname_docker`.
  # They need to be separate to allow the driver to connect to the database when both are running inside Docker.
  hostname: performance.sdk.couchbase.com
  hostname_docker: performance.sdk.couchbase.com
  port: 5432
  username: postgres
  password: password
  database: perf

environment:
  # Can override any executables here, to workaround environmental/path issues.
  executables:
  #    docker: /usr/bin/docker
    #docker: "c:\\Program/ Files\\Docker\\Docker\\resources\\bin\\docker.exe"

  # These will be added to environment variables when running executables
  envvar:
#    DOCKER_HOST: cbdyncluster docker-host docker ps

  # The workspace directory is where all temporary files will be placed
  workspace: workspace

# These settings will not be saved to the database
variables:
  # Outputs what would be performed, without actually performing it.  Config files still get written.
  dryRun: false

  # Whether to ignore whatever runs are already in the database
  force: false

  # If confident that Docker images are built and up-to-date
  skipDriverDockerBuild: false
  skipPerformerDockerBuild: false

matrix:
  clusters:
      # Currently CI is hardcoded to look for one cluster written in a specific format, so it can replace the hostname
      # In future, may return to having jenkins-sdk control cluster creation (CBD-4948)
    - type: unmanaged
      hostname: localhost
      # When run by jenkins-sdk, jenkins-sdk will use `hostname`, and the driver will use `hostname_docker`.
      # They need to be separate to allow the driver to connect to the cluster when both are running inside Docker.
      hostname_docker: cbs
      storage: couchstore
      replicas: 0
      # A number of other fields will get filled in dynamically, both by CI and by jenkins-sdk.

  implementations:
    - language: Java
      version: 3.X.X

    - language: Java
      version: snapshot

    - language: Scala
      version: 1.X.X

    - language: Scala
      version: snapshot

    - language: Kotlin
      version: 1.X.X

    # Disabling Kotlin snapshots for now as they're not building
#    - language: Kotlin
#      version: snapshot

    # Disabling .NET until performer review is completed
#    - language: .NET
#      version: 3.3.X
#
#    - language: .NET
#      version: snapshot

    # Earliest version the Go performer can compile is 2.3.0 (possibly earlier)
    - language: Go
      version: 2.3.X

    - language: Go
      version: 2.4.X

    - language: Go
      version: 2.5.X

    - language: Go
      version: snapshot

  workloads:

    # KV replaces
    - operations:
        - op: replace
          bounds:
            forSeconds: $forSeconds
          docLocation:
            method: pool
            poolSize: $poolSize
            poolSelectionStrategy: counter
      settings:
        variables:
          - name: poolSize
            value: 10000

    # KV gets
    - operations:
        - op: get
          bounds:
            forSeconds: $forSeconds
          docLocation:
            method: pool
            poolSize: $poolSize
            poolSelectionStrategy: randomUniform
      settings:
        variables:
          - name: poolSize
            value: 10000

    # KV inserts
    - operations:
        - op: insert
          bounds:
            forSeconds: $forSeconds
          docLocation:
            method: uuid
      settings:
        variables:
          - name: docNum
            value: 10000000

    - operations:
        - transaction:
            ops:
              - op: replace
                docLocation:
                  method: pool
                  poolSize: $poolSize
                  poolSelectionStrategy: randomUniform
              - op: insert
                docLocation:
                  method: uuid
            bounds:
              forSeconds: $forSeconds
      settings:
        variables:
          - name: poolSize
            value: 10000
      include:
        implementation:
          language: Java
          version: 3.3.0

# Top-level variables can be overwritten on a per-workload basis.
settings:
  # These GRPC settings are believed to give good results (CBD-4975).  GRPC settings don't get written to the
  # database, as streaming back results shouldn't affect the results themselves.  So changing these settings
  # will not trigger any reruns.
  grpc:
    flowControl: true
    batch: 1000
    compression: true
  variables:
    - name: forSeconds
      value: 300
    # Not named horizontalScaling for historical reasons - rename when we need to rerun everything
    - name: horizontal_scaling
      value: 20
